channels:
  - conda-forge
  - defaults
dependencies:
  - python[version='>=3.10']

  # Basic Dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pytz
  - requests

  # AWS
  - boto3

  # Image Processing
  - scikit-image

  # ML
  - scikit-learn
  - pytorch
  - torchvision
  - pytorch-lightning
  - kornia

  # Development / Testing:
  - jupyter
  - pylama
  - pytest
  - yapf
  - tqdm

  # Mapping / Visualization:
  - ipympl
  - ipyleaflet
  - voila[version='>=0.3']
  - psycopg2
  - sqlalchemy
  - pytables

  # GDAL Dependencies:
  - libwebp-base
  - openjpeg
  - pcre
  - poppler
  - curl
  - swig
  - cfitsio
  - charls
  - libkml
  - geos
  - cmake
  - hdf5
  - jpeg
  - zstd
  - libpq
  - freexl
  - xz
  - cgal
  - libnetcdf
  - librttopo
  - cryptopp
  - json-c
  - libtiff
  - proj
  - postgresql
  - libxml2
  - geotiff
  - libspatialite
  - expat
  - kealib
  - openssl
  - libpng
  - icu
  - libiconv
  - sqlite
  - hdf4
  - xerces-c
