# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSC_LabelHelper.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileLabel.setObjectName("fileLabel")
        self.verticalLayout.addWidget(self.fileLabel)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgLabel.sizePolicy().hasHeightForWidth())
        self.imgLabel.setSizePolicy(sizePolicy)
        self.imgLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.imgLabel.setText("")
        self.imgLabel.setScaledContents(False)
        self.imgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout.addWidget(self.imgLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imgNumSlider = QtWidgets.QSlider(self.centralwidget)
        self.imgNumSlider.setMaximum(0)
        self.imgNumSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imgNumSlider.setObjectName("imgNumSlider")
        self.horizontalLayout.addWidget(self.imgNumSlider)
        self.imgNumSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.imgNumSpinBox.setMaximum(0)
        self.imgNumSpinBox.setObjectName("imgNumSpinBox")
        self.horizontalLayout.addWidget(self.imgNumSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.inputLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLineEdit.setInputMask("")
        self.inputLineEdit.setMaxLength(10)
        self.inputLineEdit.setClearButtonEnabled(True)
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.horizontalLayout_3.addWidget(self.inputLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.basicAttrTableView = QtWidgets.QTableView(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicAttrTableView.sizePolicy().hasHeightForWidth())
        self.basicAttrTableView.setSizePolicy(sizePolicy)
        self.basicAttrTableView.setObjectName("basicAttrTableView")
        self.basicAttrTableView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.basicAttrTableView)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.labelAttrTableView = QtWidgets.QTableView(self.widget)
        self.labelAttrTableView.setObjectName("labelAttrTableView")
        self.labelAttrTableView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.labelAttrTableView)
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.screenRadioButton = QtWidgets.QRadioButton(self.widget)
        self.screenRadioButton.setChecked(True)
        self.screenRadioButton.setObjectName("screenRadioButton")
        self.overlayTypeButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.overlayTypeButtonGroup.setObjectName("overlayTypeButtonGroup")
        self.overlayTypeButtonGroup.addButton(self.screenRadioButton)
        self.verticalLayout_3.addWidget(self.screenRadioButton)
        self.sourceRadioButton = QtWidgets.QRadioButton(self.widget)
        self.sourceRadioButton.setChecked(False)
        self.sourceRadioButton.setObjectName("sourceRadioButton")
        self.overlayTypeButtonGroup.addButton(self.sourceRadioButton)
        self.verticalLayout_3.addWidget(self.sourceRadioButton)
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.opacityHorizontalSlider = QtWidgets.QSlider(self.widget)
        self.opacityHorizontalSlider.setMaximum(100)
        self.opacityHorizontalSlider.setProperty("value", 25)
        self.opacityHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacityHorizontalSlider.setObjectName("opacityHorizontalSlider")
        self.verticalLayout_3.addWidget(self.opacityHorizontalSlider)
        self.horizontalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.inputLineEdit)
        self.label_3.setBuddy(self.opacityHorizontalSlider)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSC Label Helper"))
        self.fileLabel.setText(_translate("MainWindow", "<b>File:</b>"))
        self.label.setText(_translate("MainWindow", "&Input:"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Overlay Type:</span></p></body></html>"))
        self.screenRadioButton.setText(_translate("MainWindow", "S&creen"))
        self.sourceRadioButton.setText(_translate("MainWindow", "S&ource"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">O&pacity:</span></p></body></html>"))
